In [5]:
import pandas as pd

In [6]:
movies = pd.read_csv(r"C:\GAURAV\-Python-Data-Science-To-Agentic-AI-\Python\5. Pandas\movie.csv")

print(type(movies))
print(movies.head(20))

<class 'pandas.core.frame.DataFrame'>
    movieId                                  title  \
0         1                       Toy Story (1995)
1         2                         Jumanji (1995)
2         3                Grumpier Old Men (1995)
3         4               Waiting to Exhale (1995)
4         5     Father of the Bride Part II (1995)
5         6                            Heat (1995)
6         7                         Sabrina (1995)
7         8                    Tom and Huck (1995)
8         9                    Sudden Death (1995)
9        10                       GoldenEye (1995)
10       11         American President, The (1995)
11       12     Dracula: Dead and Loving It (1995)
12       13                           Balto (1995)
13       14                           Nixon (1995)
14       15                Cutthroat Island (1995)
15       16                          Casino (1995)
16       17           Sense and Sensibility (1995)
17       18                      Four Rooms (1995)
18       19  Ace Ventura: When Nature Calls (1995)
19       20                     Money Train (1995)

                                         genres
0   Adventure|Animation|Children|Comedy|Fantasy
1                    Adventure|Children|Fantasy
2                                Comedy|Romance
3                          Comedy|Drama|Romance
4                                        Comedy
5                         Action|Crime|Thriller
6                                Comedy|Romance
7                            Adventure|Children
8                                        Action
9                     Action|Adventure|Thriller
10                         Comedy|Drama|Romance
11                                Comedy|Horror
12                 Adventure|Animation|Children
13                                        Drama
14                     Action|Adventure|Romance
15                                  Crime|Drama
16                                Drama|Romance
17                                       Comedy
18                                       Comedy
19           Action|Comedy|Crime|Drama|Thriller

In [7]:
tags = pd.read_csv(r"C:\GAURAV\-Python-Data-Science-To-Agentic-AI-\Python\5. Pandas\movie.csv")
tags.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [8]:
ratings = pd.read_csv(r"C:\GAURAV\-Python-Data-Science-To-Agentic-AI-\Python\5. Pandas\movie.csv")
ratings.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [9]:
del ratings['timestamp']
del tags['timestamp']

KeyError: 'timestamp'

In [10]:
print(movies.head())
print(tags.head())
print(ratings.head())

   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy
   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy
   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy

# data structure

In [11]:
row_0 = tags.iloc[0]
type(row_0)

pandas.core.series.Series

In [12]:
print(row_0)

movieId                                              1
title                                 Toy Story (1995)
genres     Adventure|Animation|Children|Comedy|Fantasy
Name: 0, dtype: object

In [13]:
row_0.index

Index(['movieId', 'title', 'genres'], dtype='object')

In [15]:
row_0['userId']

KeyError: 'userId'

In [16]:
'rating' in row_0

False

In [17]:
row_0.name

0

In [18]:
row_0 = row_0.rename('first_row')
row_0.name

'first_row'

# ▩ DataFrames

In [19]:
tags.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy